package com.ckemere.cubeworld.seam;

import com.ckemere.cubeworld.geometry.CubeTopology;
import com.ckemere.cubeworld.geometry.MarginSource;
import java.util.List;
import org.bukkit.World;
import org.bukkit.block.Block;
import org.bukkit.block.data.BlockData;
import org.bukkit.block.structure.StructureRotation;

/**
 * Keeps seam margins (real blocks in the void strips beyond stitched edges)
 * in sync with the authoritative terrain they mirror. Margin content is
 * derived data: generated by the chunk generator, refreshed here when real
 * blocks change.
 */
public final class MirrorService {

    private final CubeTopology topology;
    private final int marginBlocks;

    public MirrorService(CubeTopology topology, int marginBlocks) {
        this.topology = topology;
        this.marginBlocks = marginBlocks;
    }

    public int marginBlocks() {
        return marginBlocks;
    }

    /** Is this column part of a seam margin (derived, mirror-only terrain)? */
    public boolean isMargin(double x, double z) {
        return topology.geometry().faceAt((int) Math.floor(x), (int) Math.floor(z)) == null
                && topology.marginSource(x, z, marginBlocks) != null;
    }

    /** Is this column inside a cube-vertex pillar (unbreakable, immutable)? */
    public boolean isPillar(double x, double z) {
        return topology.inPillar(x, z, marginBlocks);
    }

    /** The real block a margin block mirrors, or null if not a margin position. */
    public Block sourceBlock(Block marginBlock) {
        MarginSource source = topology.marginSource(
                marginBlock.getX() + 0.5, marginBlock.getZ() + 0.5, marginBlocks);
        if (source == null) {
            return null;
        }
        return marginBlock.getWorld().getBlockAt(
                (int) Math.floor(source.source().x()), marginBlock.getY(),
                (int) Math.floor(source.source().z()));
    }

    /**
     * Push the current state of a real block out to its margin image(s),
     * rotating block states to the margin's frame. No-op away from seams.
     * Loaded margin chunks only — unloaded mirrors regenerate on load.
     */
    public void pushToMirrors(Block realBlock) {
        List<MarginSource> images = topology.marginImages(
                realBlock.getX() + 0.5, realBlock.getZ() + 0.5, marginBlocks);
        if (images.isEmpty()) {
            return;
        }
        World world = realBlock.getWorld();
        BlockData data = realBlock.getBlockData();
        for (MarginSource image : images) {
            int ix = (int) Math.floor(image.source().x());
            int iz = (int) Math.floor(image.source().z());
            if (!world.isChunkLoaded(ix >> 4, iz >> 4)) {
                continue;
            }
            if (topology.inPillar(ix + 0.5, iz + 0.5, marginBlocks)) {
                continue; // never carve into a corner pillar
            }
            BlockData rotated = data.clone();
            rotated.rotate(structureRotation(image.toSource().quarterTurns()));
            world.getBlockAt(ix, realBlock.getY(), iz).setBlockData(rotated, false);
        }
    }

    /**
     * Forward a break made in a margin to the real block it mirrors: the real
     * block becomes air and the change is reflected back into all its margin
     * images. Returns the source block that was broken, or null if the
     * position is not a forwardable margin block.
     */
    public Block forwardBreak(Block marginBlock) {
        Block source = sourceBlock(marginBlock);
        if (source == null || isPillar(source.getX() + 0.5, source.getZ() + 0.5)) {
            return null;
        }
        source.setType(org.bukkit.Material.AIR, false);
        pushToMirrors(source);
        return source;
    }

    /**
     * Forward a placement made in a margin to the real block it mirrors,
     * rotating the placed state into the source frame, then reflect it back.
     * Returns the source block, or null if not forwardable.
     */
    public Block forwardPlace(Block marginBlock, BlockData placedData) {
        MarginSource sourcePos = topology.marginSource(
                marginBlock.getX() + 0.5, marginBlock.getZ() + 0.5, marginBlocks);
        if (sourcePos == null) {
            return null;
        }
        int sx = (int) Math.floor(sourcePos.source().x());
        int sz = (int) Math.floor(sourcePos.source().z());
        if (isPillar(sx + 0.5, sz + 0.5)) {
            return null;
        }
        Block source = marginBlock.getWorld().getBlockAt(sx, marginBlock.getY(), sz);
        BlockData rotated = placedData.clone();
        rotated.rotate(structureRotation(sourcePos.toSource().quarterTurns()));
        source.setBlockData(rotated, false);
        pushToMirrors(source);
        return source;
    }

    /**
     * Forward a liquid flow that hit a seam: the margin stays inert, but the
     * flow continues on the real far side — the partner block of the margin
     * target receives the next liquid level (with physics on, so vanilla
     * spreads it from there), and the mirror reflects it back.
     */
    public void forwardLiquid(Block from, Block marginTo, org.bukkit.block.BlockFace face) {
        Block target = sourceBlock(marginTo);
        if (target == null || isPillar(target.getX() + 0.5, target.getZ() + 0.5)) {
            return;
        }
        if (!(from.getBlockData() instanceof org.bukkit.block.data.Levelled liquid)) {
            return;
        }
        org.bukkit.block.data.Levelled next = (org.bukkit.block.data.Levelled) liquid.clone();
        if (face == org.bukkit.block.BlockFace.DOWN) {
            next.setLevel(8); // falling
        } else {
            int level = liquid.getLevel();
            int spread = level >= 8 ? 1 : level + 1;
            if (spread > 7) {
                return; // out of steam
            }
            next.setLevel(spread);
        }
        if (!target.getType().isAir() && target.getType() != next.getMaterial()) {
            return; // don't overwrite solid terrain across the seam
        }
        target.setBlockData(next, true);
        pushToMirrors(target);
    }

    /**
     * Our quarter turns are counter-clockwise viewed from above (east goes to
     * north at k=1); StructureRotation's clockwise turns run the other way.
     */
    public static StructureRotation structureRotation(int quarterTurns) {
        return switch (Math.floorMod(quarterTurns, 4)) {
            case 1 -> StructureRotation.COUNTERCLOCKWISE_90;
            case 2 -> StructureRotation.CLOCKWISE_180;
            case 3 -> StructureRotation.CLOCKWISE_90;
            default -> StructureRotation.NONE;
        };
    }
}
